### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by ddaddy** [andreamazz/ViralSwitch#1]
This is great, thanks.
I don't see any reason why this shouldn't work on iOS 7, however I get this popping up yet it still runs
`[NSConcreteValue doubleValue]: unrecognized selector sent to instance`

If I add an exception break point, the app stops on this line
`self.shape.transform = CATransform3DMakeScale(1.0, 1.0, 1.0);`

Any idea how to fix this for iOS 7?

Thanks

**Comment by minhazpanara** [comment]
Good fix. :+1:
