### ISSUE TITLE
Superview's clipsToBounds property

### ISSUE THREAD

**Issue by dara---** [andreamazz/ViralSwitch#10]
Shouldn't the switch set its superview's clipsToBounds property to 'YES'? The animation did not work for me as intended until I made this change.

**Comment by andreamazz** [comment]
Hi @dara--- 
Can you provide a sample exposing this issue?

Thanks

**Comment by dara---** [comment]
```
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.

    self.view.backgroundColor = [UIColor grayColor];

    CGRect insetFrame = CGRectInset(self.view.bounds, 50.0, 50.0);
    UIView *testView = [[UIView alloc] initWithFrame:insetFrame];
    testView.backgroundColor = [UIColor orangeColor];
    [self.view addSubview:testView];

    AMViralSwitch *viralSwitch = [[AMViralSwitch alloc] init];
    viralSwitch.onTintColor = [UIColor greenColor];
    [testView addSubview: viralSwitch];
}
```

The screenshots show the difference when `testView.clipsToBounds` is toggled.

![screen shot 2015-02-26 at 10 07 31](https://cloud.githubusercontent.com/assets/8484253/6398276/55a8f49c-bd9f-11e4-9ae8-f867a5867495.png)

**Comment by andreamazz** [comment]
Ok, I see what you mean. I'm actually surprised it isn't on by default, but I'm drawing a blank on why I chose this implementation. I'll set it on as default. 
Thanks for your feedback.

**Comment by andreamazz** [comment]
Pushed version `0.2.4` with the fix
