### ISSUE TITLE
Crash on deallocate

### ISSUE THREAD

**Issue by alex566** [andreamazz/ViralSwitch#11]
AMViralSwitch adds observer for "on" keypath in "didMoveToSuperview" delegate method, which is called twice (on adding to superview and on removing from one), but view removes observer one time in dealloc method.

**Comment by andreamazz** [comment]
Hi @alex566 
You are right about the observer possibly set twice, but I don't understand why it would crash. Can you post the stacktrace?

**Comment by andreamazz** [comment]
In the meantime checkout latest commit for a possible fix.

**Comment by alex566** [comment]
<img src="http://content.screencast.com/users/Aleksey566/folders/Jing/media/e454cb22-a374-480a-b48b-ceeb5d88b730/00000013.png"/>

**Comment by andreamazz** [comment]
Does this happen even with the latest commit?

**Comment by AmauryVela** [comment]
Yes

**Comment by andreamazz** [comment]
Can you provide a sample to reproduce the issue?

**Comment by AmauryVela** [comment]
https://github.com/AmauryVela/test_virals

I'm new with git so i dont know if theres another way to show you an example.

Cheers

**Comment by andreamazz** [comment]
The way is fine, the sample is not. It would be nice to have a sample that compiles without having to hunt down dependencies... Most of all it would be best to have the steps to reproduce the crash. After getting the sample to compile I tried to tap around (the foreign language doesn't help) but got no crash (beside the one due to the missing segue).

**Comment by alex566** [comment]
Yes, latest commit fixes the issue, when I write this code manually. Could you please include this commit in pod to apply changes?

**Comment by andreamazz** [comment]
Great. I've pushed the new pod, version `0.2.5`
