### ISSUE TITLE
Does not work on ios 9

### ISSUE THREAD

**Issue by diretix** [andreamazz/ViralSwitch#15]
Im Tryed to use it with ios 9.2 and it is not working. the error i getting: 

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UISwitch setAnimationDuration:]: unrecognized selector sent to instance 0x7feb08f1a510

**Comment by andreamazz** [comment]
You are calling `setAnimationDuration:` on a plain UISwitch. Make sure to set the proper class on the switch that you want to animate.

**Comment by diretix** [comment]
I have set the AMViralSwitch instead of UISwitch in the outlet, Im I need to set anything else?

**Comment by andreamazz** [comment]
You need to set the proper class in the object on the storyboard

**Comment by diretix** [comment]
Yea, working now, but there is a problem, when i tap it on, the color not covering all the screen, maybe it beacuse i using a switch inside anoder uiview in main view?

**Comment by andreamazz** [comment]
Yep. The switch covers only its first subview.

**Comment by diretix** [comment]
okay, Thanks for help!))
