### ISSUE TITLE
disappearing border while scrolling table 

### ISSUE THREAD

**Issue by lutc** [andreamazz/ViralSwitch#16]
![2016-05-31 14 53 51](https://cloud.githubusercontent.com/assets/1345360/15673487/a45df3e8-273f-11e6-8df0-44d93ea705d4.png)
Hello. I've found the following bug. I use ViralSwitch in my UITable and have some cells for more than one screen. When I switched on the top switcher and scrolled table to bottom and again to top - border of switcher  disappeared.
I've fix this by changing one string of code:
AMViralSwitch.m:- (void)switchChanged:
Line 80
old: self.layer.borderWidth = 0;
new: self.layer.borderWidth = 1;
And result after scrolling:
![2016-05-31 15 00 18](https://cloud.githubusercontent.com/assets/1345360/15673584/68a0a2dc-2740-11e6-9668-3eb2dcd07292.png)

I don't know the reason of setting border to 0, but changing this code will fix bug that I've found

**Comment by andreamazz** [comment]
Hi @lutc 
Thanks for pointing that out. It's fixed in `1.0.1`
